### PR TITLE
Add kraft.cloud.yaml

### PR DESCRIPTION
**Pull request by razvand**
This is to be used for KraftCloud deployments.

### CODE REVIEW

**Review by marcrittinghaus — COMMENTED** [review]
I think, it makes sense to remove all targets that are not runnable on KraftCloud and also name the KraftCloud target accordingly. Also 9pfs is not supported on the plat. initrd is also the only option.

**Comment by razvand** [comment]
> I think, it makes sense to remove all targets that are not runnable on KraftCloud and also name the KraftCloud target accordingly. Also 9pfs is not supported on the plat. initrd is also the only option.

@marcrittinghaus, done.

**Review by StefanJum — APPROVED** [review]
There are some firecracker networking issues unrelated to this pr. This is fine.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by marcrittinghaus — APPROVED** [review]
Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
