### PR TITLE
kraft.yaml: Add configuration to use Musl

### PR DESCRIPTION
**Pull request by razvand**
Add configuration to use Musl instead of newlib and pthread_embedded.

### CODE REVIEW

**Review by mariasfiraiala — COMMENTED** [review]
Looks good, but would it make sense to also add `ARM` as an architecture, the way you did for this [PR](https://github.com/unikraft/app-micropython/pull/3/files#diff-43f43c426dc10c1826a3004e0dc8d5da2b2a2d1a2136c14cd0960e5100b2dd39R14)?

**Comment by razvand** [comment]
> Looks good, but would it make sense to also add `ARM` as an architecture, the way you did for this [PR](https://github.com/unikraft/app-micropython/pull/3/files#diff-43f43c426dc10c1826a3004e0dc8d5da2b2a2d1a2136c14cd0960e5100b2dd39R14)?

@mariasfiraiala , solved

**Review by mariasfiraiala — APPROVED** [review]
All good now. Thank you @razvand !

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by nderjung — COMMENTED** [review]
Looks good to me! Thanks!

Approved-by: Alexander Jung <alex@unikraft.io>

**Pull request closed without merging**
